language: node_js
deploy:
  provider: heroku
  api_key:
    secure: p9Dz+to3WSx2lXtVlShdn+cSnYBNmxHfPRc6rf0tkCbboB8NF8lQE8BIFG3lfhaZJVxRJeQ19IYr6v1l3LzY72ndSBv6D6erwjTaMTcFjUDNgKvIVFm4guM3JoNC3zM4O02knFxcK/vA2HvVNtIkuzC56nk7+HA538FGvO/otnPcMWjvd9u/kQRDG0XraLJJiYhMMn73h30E5TJQcN8J4ao+XqDDOsamkQ3cnWyTsj3bOWSpHab2uK1zwRZYub/5pFE2F9qX4X5S5nfLlslmnxHgG5iFx295dRYzg2kQ3FDtFmKOnU+u1FNi6ZqrjPR/a+ECQzHHbuo9GelIS9bIMfpjjdb5UaAARXkZu0WkpCj5RCBQQQPi6RUGpZCPiPtGortn+VvjUEqLpqBFBLfoImWbCBuw9rywDgw4VHWMxwLCvdtVE5PrZwLwDSeOC0SejBaWdIhZwvRF1IYjlJhdbEjeYPO85Keo/uhsWN5cmr/Dle/RElhpWFf897HSeZFMPaXlIxQ2bg0ybmLDmizjeiNwgbueFkXJqOgpwEimqsb8Is7VOplFNeggJf1dM5ELk0IQqkTxPLCcxDOAiY8dFefQ4Nt5/t4v6LhTt/XnN1kfOZhRMrX9A5LDoGraSH1u1QF1tmbwXPs4VdU7bfGT7zh8bcfKz31FFSGbNNFVinw=
  app: stretto-demo
