language: node_js
node_js:
- node
script: npm run build
deploy:
  - provider: releases
    api_key:
      secure: sf5hAKdrmfHWHqAJfos7LlZQ9zmZKJWKaVjZvAQV2RwN6J1CxcK2buKg9As0v+N2VibPj9P+hc6qBcEUs8ChVWTdw6FCHX+8q9oHTOuwj14zuiOnOk6lna+zvFDaQ6PSkDfM7bWmCdwBPUHvA+sGQQ1tLwLW49e9IQ4rp0XTNXmaUlizvvRlyd2pF9q9MGBY0txcTu7CBvMjPLdyNzjAuUYiyEAR6ZpTfgdHwofusPH87tf1WDp1rro+qRW5KbTdgPeEtNVnHLRYhost7+CrhFAcFUIBx7NV837SUNMtpMGyVT+KrnkgVhcNA3P5wGerShUOLJWNYnFPMV/M8wkq2MKae79Ur30X5jBJ/S61BOyvCaopfxFv9xAiPtowmFk7fGIGkv1NcZWQfJEm0KcZnPkd5yYCfQuVyYLssVp8OpIYgOR00QdmzTYe7Joj0KTPO8jOBQwZo9ccncbw5Bg2WLfBOroiwzpxdmWbVHmrqsmcXHptWMmjR9aPXKxe6wo04Aujb/8oSZOPAf1tlDIaw7bK/8WaJjvBiaX/9Oel8oYHuVPIxJ/aTB2oZgj2Q/iaQAlrIF/R4QNZ8yaP0phqNF1eTRo0oCa6rQdqK/Ce/tPMfpI/byFPZkZBcWX0rR7PASxwapUjCD/C/pd+mwdW6rEjzP2NzOcTo0+ISJIpkTI=
    file:
     - electronres/Stretto-darwin-x64.zip
     - electronres/Stretto-linux-x64.zip
     - electronres/Stretto-win32-x64.zip
     - electronres/Stretto-linux-arm64.zip
     - electronres/Stretto-linux-armv7l.zip
     - electronres/Stretto-win32-ia32.zip
     - electronres/Stretto-linux-ia32.zip
    on:
      repo: ohnx/stretto
  - provider: heroku
    api_key:
      secure: p9Dz+to3WSx2lXtVlShdn+cSnYBNmxHfPRc6rf0tkCbboB8NF8lQE8BIFG3lfhaZJVxRJeQ19IYr6v1l3LzY72ndSBv6D6erwjTaMTcFjUDNgKvIVFm4guM3JoNC3zM4O02knFxcK/vA2HvVNtIkuzC56nk7+HA538FGvO/otnPcMWjvd9u/kQRDG0XraLJJiYhMMn73h30E5TJQcN8J4ao+XqDDOsamkQ3cnWyTsj3bOWSpHab2uK1zwRZYub/5pFE2F9qX4X5S5nfLlslmnxHgG5iFx295dRYzg2kQ3FDtFmKOnU+u1FNi6ZqrjPR/a+ECQzHHbuo9GelIS9bIMfpjjdb5UaAARXkZu0WkpCj5RCBQQQPi6RUGpZCPiPtGortn+VvjUEqLpqBFBLfoImWbCBuw9rywDgw4VHWMxwLCvdtVE5PrZwLwDSeOC0SejBaWdIhZwvRF1IYjlJhdbEjeYPO85Keo/uhsWN5cmr/Dle/RElhpWFf897HSeZFMPaXlIxQ2bg0ybmLDmizjeiNwgbueFkXJqOgpwEimqsb8Is7VOplFNeggJf1dM5ELk0IQqkTxPLCcxDOAiY8dFefQ4Nt5/t4v6LhTt/XnN1kfOZhRMrX9A5LDoGraSH1u1QF1tmbwXPs4VdU7bfGT7zh8bcfKz31FFSGbNNFVinw=
    app: stretto-demo
